### ISSUE TITLE
Install Pip Packages not working

### ISSUE THREAD

**Issue by homemadestea58** [holzschu/a-shell#183]
Hi,

I am having some trouble installing pip packages in a-Shell on my iPad.

The error I am getting is:
`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Applicatio
n/B9F3AD4B-6E02-4A8F-9909-B9CAD056C5C1/tmp/pip-req-tracker-jsh63kyq/b3d11b549c9c3e6f867cf8139a0b646bd887c50dacaef8554fa07625'`

Any help would be greatly appreciated

**Comment by holzschu** [comment]
Hi, 
which packages were you trying to install? I'd like to reproduce the issue.

**Comment by homemadestea58** [comment]
Hi,
The packages were netifaces and netaddr

**Comment by holzschu** [comment]
In my tests, netaddr can be installed, but netifaces cannot, because it needs a compiler to compile C extensions (the actual error is somewhere in the middle of the long error message, "There are no compilers available on iOS").

I believe the shell command `ifconfig` can answer some of your questions about network interfaces.

**Comment by homemadestea58** [comment]
Thank you for your time and help!
