### ISSUE TITLE
CWD: Acts like it's in PATH, but isn't in `$PATH` env variable.

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#223]
### My `$PATH`
```sh
$ echo $PATH
/var/mobile/Containers/Data/Application/F10482C
1-F834-472C-83C3-7DAFD373F546/Documents/perl5/b
in:/private/var/containers/Bundle/Application/2
2870809-6DD7-4608-B850-B534B251760D/a-Shell.app
/bin:/private/var/containers/Bundle/Application
/22870809-6DD7-4608-B850-B534B251760D/a-Shell.a
pp/Library/bin:/private/var/containers/Bundle/A
pplication/22870809-6DD7-4608-B850-B534B251760D
/a-Shell.app/Library/bin3:/var/mobile/Container
s/Data/Application/F10482C1-F834-472C-83C3-7DAF
D373F546/Library/bin:/var/mobile/Containers/Dat
a/Application/F10482C1-F834-472C-83C3-7DAFD373F
546/Documents/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ pwd
/private/var/mobile/Containers/Data/Application/F10482C1-F834-472C-83C3-7DAFD373F546/
Documents/Programming/Build/xxd.git
```

### Summary
Although `$PATH` doesn't seem to contain my current working directory (or `.`), executables placed in the current working directory override those in `$PATH`.

### For example,
A broken `jsi` executable in the current directory overrides the global `jsi`:
```sh
$ ls
jsi
$ pwd
/private/var/mobile/Containers/Data/Application/F10482C1-F834-472C-83C3-7DAFD373F546/
Documents/tmp
$ jsi
  File "/private/var/mobile/Containers/Data/Application/F10482C1-F834-472C-83C3-7DAFD
373F546/Documents/tmp/jsi", line 3
    this will break
         ^
SyntaxError: invalid syntax
```

### Notes
 * See also https://unix.stackexchange.com/questions/65700/is-it-safe-to-add-to-my-path-how-come
 * **This might be expected behavior! If so, please disregard!**

**Comment by holzschu** [comment]
It's a... complicated issue, between what users expect and security. I am fully aware of the safety issue you mention, but most users aren't, and they complain when commands in the current directory aren't executed. Given the strong security introduced by the iOS Sandbox plus the limited amount of commands, that seemed like a good compromise in the beginning. I may have to re-evaluate this in the future, since more and more commands are becoming available.

**Comment by personalizedrefrigerator** [comment]
That makes sense! Thank you!
