### ISSUE TITLE
Can I run ImageMagick from the Shortcuts extension?

### ISSUE THREAD

**Issue by atnbueno** [holzschu/a-shell#280]
When I try to run the `convert -size 40x40 xc:red red.png` command from the Shortcuts extension, I get the following error message:
_"convert: UnableToOpenConfigureFile `colors.xml' @ warning/configure.c/GetConfigureOptions/703"_

Probably related: I've seen that ImageMagick environment variables (which I've seen with `env` in the app) are not available in the extension environment (I've run the `env` command from the extension). If this is the cause of the problem above, is there any way to have the same environment in the app and the Shortcuts extension?

**Comment by atnbueno** [comment]
Agh. Again, now that I've reported the problem, it works.

**Comment by holzschu** [comment]
Hi,
I've seen all your issues. For most of them, I'll need to think about it to get the answer, but this one is easier. From Apple's point of view, the extension and the app are two different applications, with different applications directories. ImageMagick requires many auxiliary files to operate, and these files are in the main application directory (the environment variables are just there to give the position of the auxiliary files, because it changes every time the App is upgraded). I haven't copied these auxiliary files to the extension directory, so it makes sense that `convert` can not run in Extension, only in App. I'm actually surprised that it works, I'll have to test it.

So far, my thinking has been: if a command requires auxiliary files, it should be run in App, but that was mostly guided by the commands that require huge directories of aux files, like python or clang. It might be a good idea to rethink this policy now.

**Comment by atnbueno** [comment]
As I said in the other issue, this works always and everywhere now:
https://www.icloud.com/shortcuts/699450d555e241c9ba86e54fc17f6bb3

**Comment by holzschu** [comment]
Yes, but that shortcut is running in App, and then calling "open Shortcuts://" to get back to shortcuts. That makes sense.

Running more experiments, I think I found something: sometimes the shortcut will run (in App), *then* change directory before displaying the window. If you run `ls` to check if the file exists, you won't find it, giving the impression that the shortcut didn't run. This *may* be what happened earlier. I'll need more experiments.

**Comment by atnbueno** [comment]
Does it run in the app? I selected "Run in extension" in the "Execute shell command" action ("Keep going..." and "Show When Run" disabled)

**Comment by holzschu** [comment]
Oh, I was wrong and you are right, it runs in extension. It even works if I remove the "open shortcuts://" line.
Ah, it seems the `UnableToOpenConfigureFile` message is only a warning, not an error. So convert is able to continue, and does the file creation. It might not work for other commands, though.

**Comment by atnbueno** [comment]
I think this, together with the directory change, explains most of the weird behavior I experienced.

I'll keep experimenting with what in ImageMagick works in the extension. Image processing is a particularly lacking subject in Shortcuts.

Thanks for the interest! 🙂
