### ISSUE TITLE
Feature Request: opencv-python

### ISSUE THREAD

**Issue by lewisxy** [holzschu/a-shell#309]
Can you bundle the [opencv-python](https://pypi.org/project/opencv-python/) (and opencv-contrib-python) to a-shell? I can't install it via pip as it needs native C++ library (actually trying to install it results in a dead loop where pip repeatedly trying to download the package but failed, and cannot be stopped without restarting the app). I suppose the process will be similar to numpy. Thanks.

**Comment by holzschu** [comment]
Well, the good news is, I have compiled OpenCV for iOS and opencv-contrib (if you want to get technical, it's opencv_contrib_python_headless, for obvious reasons). It will be in the next release.
The bad news is, all those builds (since July 5th) have been sitting in limbo: not rejected, not accepted, no way to know what's going wrong. I am engaged in a polite but so far fruitless discussion with Apple Developer Support.

About the infinite loop: that's a new feature of pip. If installing a package fails, for whatever reason, it will try to install the earlier version, until it works. Since opencv-python version 4.5.2 has failed, it will try version 4.5.1, then 4.5.0, then 4.4.9, then...

**Comment by lewisxy** [comment]
I see, thanks for including it in the next release. Hopefully it will get approved soon.

For the pip retry loop, are there anyway to disable it? It's better if it can be done with some special pip flags.
After I saw the retry loop, I suppose I should be able to terminate it with ^C, but that doesn't seem to work in a-shell.

**Comment by lewisxy** [comment]
Thanks, I just tried Carnet, and it's overall pretty good. Hopefully it can get to App Store soon.

> The Python present on a-Shell is more limited than the Python on Carnets, to limit the size of the app (it's already quite big).

> The latest build of a-Shell has Pandas, but I am not planning to go beyond that.

The size of a-shell currently listed on App Store is around 982MB, which is still manageable in my opinion. Considering most of our devices are having a increasingly large storage (for example, the latest iPhone (iPhone 13) has a minimum storage of 128GB), the convenience of including more packages outweighs the cost of a slightly bloated binary, especially given the fact that **users cannot install additional binary themselves** due to Apple'e special code signing policy. In addition, since we have a-shell mini, which is a compact version of a-shell, users are more inclined to expect that a-shell offers a more complete experience.

The above is just my opinion. In any case, I respect whatever is your final decision, and appreciate the amazing software you have built.
