### ISSUE TITLE
Variable : command not found

### ISSUE THREAD

**Issue by Mara-Li** [holzschu/a-shell#310]
Hello! 
As the `find` doesn't seem to work with accented characters (like `é`), I try to work with `sed` to remove it, but when I do this : 
```sh
$VAR=$(echo été|sed 's/é/e/g')
```
I have as result `$VAR=$(echo: command not found`

When I try to export, the `space` between echo break all...

Anyone had a workaround idea?

**Comment by holzschu** [comment]
The syntax `$VAR=something` is not implemented in a-Shell. `setenv` and `export` are both implemented, though. Also the syntax `$(command)` is not implemented either.

This being said, a quick test on my platform shows that `find` works with accented characters. I might be able to provide more help if you could give me an example of the command you are trying to run with find.

**Comment by Mara-Li** [comment]
Well, I have a folder with a lot of MD file.
One is named "Prévention des infections croisée"

When I try `find . -name Prévention des infections croisée.md`, I don't have anything : 
![image](https://user-images.githubusercontent.com/30244939/133687268-c13caa4c-ad9b-4724-b3fe-598b52ac4253.jpeg)

I found that ashell seems to add a strange character after the accented char : ![image](https://user-images.githubusercontent.com/30244939/133687450-f1bc7533-4051-4564-83be-f353e0591d04.jpeg)

**Comment by holzschu** [comment]
Thank you very much. That is a very interesting question.

If I create the files locally, inside a-Shell, they are encoded as "Présentation", and `find` does find them. I assume your files have been copied from a different computer, which uses a slightly different way to encode accented characters like "é", that is sufficiently standard to be printed as "é", but different enough that, internally, it does not match "é".

Your second image shows that "é" has been encoded as "e + plus backward character with acute accent". Hence your `find . -name "Pre*"` works, and `find . -name "Pré*"` does not (I have the reverse behaviour on my own iPad, because I created the files locally, so "é" is encoded as "é").

Since renaming all those files would be impractical, I would suggest `find . -name "Pr*vention *"`, but that might be insufficient for your needs.

**Comment by Mara-Li** [comment]
I fact, I can write a little python script using `unidecode` to treat these things with `os.walk`. Not the best work around, but working great !
