### ISSUE TITLE
Shortcuts : return value in shortcuts

### ISSUE THREAD

**Issue by Mara-Li** [holzschu/a-shell#311]
I want to know if it's possible to return value in shortcuts, to do a choice ; and after, return in a-shell. 

For exemple, I want to create a python script to "just" choice a file. But file can be multiple (as I can't have the folder in the shortcuts sheet). 
So, for example, if I have multiple "Introduction" file, in folder A, B, ... I want to return the list in shortcuts to choice the good folder. After this choice, I want to return to a-shell to do action on the file.

So **how can I return the list to shortcuts** ?

**Comment by holzschu** [comment]
If the shortcut runs in extension, you can output the list to standard output. Otherwise, I would output the list to a file and read that file.

**Comment by Mara-Li** [comment]
How can I output the list to standard output ?

**Comment by holzschu** [comment]
For a shortcut running in extension: anything a command writes (with print() in Python, or ls -1, or...) is sent to the standard output and is available as input for the next step in Shortcuts (just connect the two actions).

For a shortcut running in app: it's a bit trickier. First redirect the output to a file (python script > file), then call open shortcuts:// to get back to shortcuts, then get the file with the get file action.

**Comment by holzschu** [comment]
For the first one, it looks like this:
![716FFC8F-9BED-4D86-B3AC-F020BBB6475D](https://user-images.githubusercontent.com/8070736/133884581-2355f400-5aab-46fb-9754-d938ab13db4a.png)

**Comment by Mara-Li** [comment]
Okay ! I will try to trick with that ! Thank you a lot, a-shell is a very powerful tool.

**Comment by Mara-Li** [comment]
Sorry for the very late reply !
I try to create a shorcuts to get the file, but I don't have anything in output / Quick Look. 
I try : 
```
cd variable_folder
ls
```
`cd variable_folder | ls` 

By none work :/ With the first, I have the good output in the app.

**Comment by holzschu** [comment]
It's a bit difficult to understand what is happening with only the commands, without the environment and the rest of the shortcut. One possible explanation would be that you have two folders with the name `variable_folder`, which would explain the difference of behaviour in extension and in the app. 

All shortcuts are executed in a separate directory, `~shortcuts` or `$SHORTCUTS`, while the app is running in `~/Documents`. A shortcut running in extension does not have access to `~/Documents`, only to `~shortcuts`. The app has access to both.

**Comment by Mara-Li** [comment]
Well, I try also with just only a shortcuts to get a list of my bookmark and i don't have anything in quickloock.

Here is the shortcuts : https://www.icloud.com/shortcuts/c0d4bb6bd47a4bd093fe85aeb763e4e7

**Comment by holzschu** [comment]
Thanks. I think I see what the problem is. The extension is a separate app from the main app, so they don't share bookmarks, for example, and it cannot access the main screen. So both `pickFolder` and `showmarks` won't work "in Extension" (which is why Shortcuts launches the app). And the notion of standard output only exists for shortcuts running "in Extension", for shortcuts running in App the standard output is managed by the App. 

What you can do is have your shortcut run the following commands in App:
```
showmarks > temporaryFile
open shortcuts://
```
then run this command in Extension:
```
cat temporaryFile
```
The `open shortcuts://` line will go back to the Shortcuts app once the first command is executed. The Shortcuts app will then execute the next action (`cat temporaryFile`) which will produce a standard output that you can then manage within the Shortcuts app.

**Comment by Mara-Li** [comment]
It's a good idea ! I will try :D
