### ISSUE TITLE
Vim doesn't accept any key input when displaying fern.vim in a-Shell 1.7.6 (189) or later

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#318]
## Description

Vim doesn't accept any key input when using [fern.vim](https://github.com/lambdalisue/fern.vim) on a-Shell 1.7.6 (189) or later.

This issue doesn't occur when fern is just loaded, but it does when fern is displayed, e.g. by `:Fern .`.

I tested several versions of a-Shell, and I found that this issue occurred only in a-Shell 1.7.6 (189) and later, but not in 1.7.6 (187) and earlier.

![36C99783-CC64-4DD6-8D82-1DE5C37C461F](https://user-images.githubusercontent.com/601636/135754526-5e4ba6fc-a4e2-4a3b-bb37-150561670497.png)

## Environment

- 12.9-inch iPad Pro 5th generation
- iPadOS 15.1 Developer Beta 2
- My `.vimrc` and `.vim` are available [here](https://github.com/kkk669/dotfiles)

**Comment by holzschu** [comment]
I think build 189 is the first to introduce mutex locks to avoid issues when multiple commands start or end at the same time. It was necessary in order for long Perl scripts to work, but it causes issues elsewhere.

I was hoping that build 194, with atomic variables, would fix the issue, but apparently not. I'm going to have a look (it's probably a symptom of something more problematic).

**Comment by holzschu** [comment]
Found it (the fix will be in build 195).

Long explanation: 

The new version of ios_system introduces locks (mutex_locks) when we fork (from the call to fork until the time the thread ID is stored and associated with the pid), when we terminate a command (from the time stdout is closed to the time the thread ID is de-associated with the pid) and when we change directory (to avoid another command changing the running directory while a command is starting). All of this was necessary in order to run the long Perl scripts that come with TeX, where I had lots of commands starting, and some of them starting before the previous command had finished cleaning up. But of course, if a program like Python or Vim forks, then changes the working directory before launching the command, then we have multiple locks and nothing works anymore. That is relatively easy to find and fix (there is a version of chdir that does not lock, specifically for these cases).

To be complete, the lock when a command is terminated is different, to allow multiple commands to terminate simultaneously, which is necessary because we can run multiple commands, such as `ls | grep`, and one of them may be waiting for the other to terminate. So there is an atomic counter, all commands can terminate, but no command can start until all commands have been terminated.

**Comment by kkk669** [comment]
@holzschu Thank you for the detailed information.

> there is a version of chdir that does not lock, specifically for these cases

However, doesn't that cause the following problem you described above? Am I missing something?

> another command changing the running directory while a command is starting

**Comment by holzschu** [comment]
> However, doesn't that cause the following problem you described above? Am I missing something?

That's, technically, the same command. Most of the time, you have fork + exec, but in some cases, `mch_job_start` goes fork + chdir + exec. The lock is already in place, and the chdir only applies to the current command, so calling the chdir-with-no-lock function does not harm.

**Comment by holzschu** [comment]
Build 195 is now released. It solves the problem on my side.

**Comment by kkk669** [comment]
I understand [your explanation](https://github.com/holzschu/a-shell/issues/318#issuecomment-933172527), and confirmed that the problem had been solved on my side as well. Thanks a lot!
