### ISSUE TITLE
Add apt package manager

### ISSUE THREAD

**Issue by hmsjy2017** [holzschu/a-shell#327]
Termux under Android can be used without root permission and supports the apt package manager. The principle is that all software Android NDK is cross-compiled, and only compatibility patches can make them run on Android. Therefore, through cross-compilation, I think it is feasible to add the apt package manager to a-Shell.

**Comment by holzschu** [comment]
iOS security rules are stricter than Android. In order to be executed, or loaded as a dynamic library, a binary must be:

1. cross-compiled for iOS (difficult, but I've been doing it for a long time)
2. signed with the developer certificate (easy)
3. placed in a directory that can only be accessed when the app is being installed.

With those rules, there is no way (to the best of my knowledge) to have a package manager inside an iOS app. It is also incompatible with AppStore rules (all binaries must be submitted for app review, the user can only add text files that they can read to check what they do).

**Comment by Practicalbutterfly5** [comment]
iSh for ios also uses alpine package manager “apk”. Can something similitude  done?

**Comment by holzschu** [comment]
iSh goes around the iOS restrictions with their package manager because they are not, technically, installing iOS binaries, but x86 binaries that will be interpreted. So they can install anything, but it won't be fast.
