### ISSUE TITLE
TeXLive fonts problem

### ISSUE THREAD

**Issue by NVfly** [holzschu/a-shell#343]
Hello there!

I ran into a problem trying to compile a document in russian using texlive integrated in a-shell. It says me the following info:

`/Library/texlive/2021/texmf-dist/tex/latex/cyrillic/t2acmr.fd
File: t2acmr.fd 2001/08/11 v1.0a Computer Modern Cyrillic font definitions
)
! Font T2A/cmr/m/n/12=larm1200 at 12.0pt not loadable: Metric (TFM) file not fo
und.
<to be read again> 
                   relax 
l.5 \babel@aux{russian}{} `

I thought it just unable to find the Cyrillic fonts package, but tlmgr says all is installed. Same .tex source is ok on Mac (MacTex) and overleaf. In general, any .tex with Russian babel gives this error.
I suspect some troubles with writing permission.

**Comment by holzschu** [comment]
Hi,
Now that is a very interesting question. From what I can gather, fonts with russian encoding (T2A...) are installed using metafont files. The first time a TeX file asks for a font with russian encoding, it calls `mktextfm larm1200` to generate the tfm and pk files. Of course, this needs to be done only once. This explains, I think, why it works on a Mac and overleaf. I have not cross-compiled metafont (yet), so `mktextfm` fails.

I'm not sure if that is the best answer for you, but a possible solution is to switch to *modern* TeX, using `lualatex` and its UTF8 encoding rather than the multiple encodings of old TeX. 
```TeX
...
\usepackage{fontspec}
\usepackage{polyglossia} % Replaces babel
\setmainlanguage{russian}
\setmainfont{LinLibertine_R}[Script=Cyrillic]

\begin{document} 
```

And of course you can write files in multiple languages. Another solution would be to copy the t2a*.tfm files from an existing TeX install into `~/Library/texlive/texmf-local`.

**Comment by NVfly** [comment]
Thank you very much for the explanation. I was too excited to make it work so I didn’t even check metafont. Now I can fix it.

Alright, one more question: is it correct that the folder `texmf-local` placed in `~Library/texlive/2021`, but not in `~/Library/texlive`? So running `mktexlsr`, for example, fails to find it.

**Comment by holzschu** [comment]
No, that sounds like a bug. Is there anything in your `texmf-local`? (there are two operations that create `texmf-local`: one when moving from an old install, we copy `texmf-local` to the new install and erase everything else, the other when installing a new system).

**Comment by NVfly** [comment]
I did a fresh install of a-shell, just found it yesterday (and I already in love :) ), so it’s definitely done by default.

**Comment by holzschu** [comment]
After checking: the install process was creating this `texmf-local` in the wrong place. You should create your own `texmf-local` in `~/Library/texlive`.

**Comment by NVfly** [comment]
I did already.

Moving .tfm files to that folder really solves the problem, until another document which requires different font size/shape. Anyway, it works and it’s on iPad. Thanks again!

**Comment by holzschu** [comment]
Thanks for pointing the issue with `texmf-local`. It will be fixed in the next release.

**Comment by NVfly** [comment]
Thanks again! I think we can mark it as closed.
