### ISSUE TITLE
caffeinate?

### ISSUE THREAD

**Issue by NightMarekApps** [holzschu/a-shell#353]
Hi thank you for adding a feature recently that keeps the screen awake when process is running. I have an idea. There are other apps that don't keep the device unlocked, for example files, but there are countless more.

Would it be possible to add an empty process that does nothing and keeps the screen awake (and maybe even specify the duration)?

Thanks and happy holidays!

**Comment by holzschu** [comment]
Adding that as a default command would be playing dangerously close to the AppStore restrictions. But if a user creates a small program in Python or C that just asks for input and does nothing else, then stops when the user has entered input well... that would work.

However, there are other limitations in the system: an app in the background can always be terminated by the system, so you would have to keep both a-Shell and Files in the foreground, so that would work only on an iPad.

**Comment by NightMarekApps** [comment]
Thanks, that advice will be handy when downloading huge files or transferring files from drives. yeah I meant split screen or slide over
