### ISSUE TITLE
Should we able to autocomplete paths/filenames on remote machines?

### ISSUE THREAD

**Issue by arpitgupta** [holzschu/a-shell#354]
Currently it does not. I was not sure if this is feasible or not.

**Comment by holzschu** [comment]
Hi, 
I assume you mean, "when ssh-ing to a remote machine, should we be able to autocomplete the file name by typing tab".

I tested it on my machine, and it worked. Which is good news, because it means it's a question of personal settings rather than an issue with the application. You should check the value of the `TERM` environment variable on the remote machine, and try if changing it to `xterm` or `xterm-256color` improves things.

**Comment by arpitgupta** [comment]
I tried 2 different machines one is a Synology NAS and other a Pi3. Both have `TERM` set to `xterm-256color` and auto complete would not work. I tried changing `TERM` to `xterm` and still no luck.

**Comment by arpitgupta** [comment]
Ok interesting it works some times. What i have found out is that if `vi somefile` and close it then auto complete starts working. Otherwise it keeps adding a tab.

Weird :).

**Comment by holzschu** [comment]
I would suggest comparing the environment (`env`) before and after `vi`. There maybe something that `vi` sets that enables autocomplete.

**Comment by arpitgupta** [comment]
good idea. Tried it and no difference in the env before and after.

**Comment by holzschu** [comment]
Okay, so it's not the environment variables. It might be some options to the shell you are running.

**Comment by arpitgupta** [comment]
Ok. I will research and see what i can find out. FTR i have a chromebook from which i ssh into those machines and auto complete works without any issues.
