### ISSUE TITLE
Scikit

### ISSUE THREAD

**Issue by ifuchs** [holzschu/a-shell#369]
Apologies if this has already been asked (I did not see it in Issues). Would it be feasible to add scikit to available python libraries?

**Comment by holzschu** [comment]
You mean scikit-learn? It's technically feasible (since it's already in Carnets), it's just that I'm not certain that it's worth it for enough users, given the extra size it would bring. I was under the impression that graphics-oriented Python modules make more sense in a graphics-oriented application like Carnets.

**Comment by ifuchs** [comment]
I think you are right. Scikit–learn is best used in Carnet.
