### ISSUE TITLE
“No space left on device” error

### ISSUE THREAD

**Issue by dmedwards** [holzschu/a-shell#473]
I'm getting a “No space left on device” error when working with large files (>10GB). 

I have been able to replicate the error by asking ffmpeg to generate a 1-minute 4K video.

`ffmpeg -f lavfi -i testsrc=duration=60:size=3840x2160:rate=30 -c:v copy -y testsrc.ts `

Copying large files can also produce this error even though there is sufficient space on the device. 

Is there a workaround for this?

**Comment by holzschu** [comment]
That's a good question. I have no idea what is happening, but since a-Shell is using iOS system calls to write files, I suspect the limit comes from iOS. Looking up on search engines, the 10GB size limit for files is mentioned a few times for iCloud, but not for local files. I'll run a few tests to investigate.

**Comment by dmedwards** [comment]
Thanks for looking into this. The ffmpeg command line did eventually complete without errors on my devices after several attempts. It's almost as if iOS allocates more space with each run.
