### ISSUE TITLE
Is it possible for the clang in app to build executables?

### ISSUE THREAD

**Issue by NeHyci** [holzschu/a-shell#517]
I tried running these commands:
```
clang -target arm64-apple-darwin19.6.0 -isysroot iPhoneOS14.4.sdk -c main.c
```

But I got the error:
```
ld: error: unknown argument '-dynamic', did you mean '-Bdynamic'
ld: error: unknown argument '-arch'
ld: error: unknown argument '-iphoneos_version_min'
ld: error: unknown argument '-syslibroot'
ld: error: cannot open arm64: No such file or directory
ld: error: cannot open 14.4.0: No such file or directory
ld: error: cannot open /var/mobile/Containers/Data/Application/42A6D41D-2D9B-4A42-B640-6A0D44CB4C1F/Library/usr: Is a directory
ld: error: /private/var/mobile/Containers/Data/Application/42A6D41D-2D9B-4A42-B640-6A0D44CB4C1F/tmp/main-ba7b6b.o: unknown file type
ld: error: unable to find library -lSystem
```

**Comment by holzschu** [comment]
Hi,
You cannot build an Arm64 executable on iOS and make it run on iOS, unless your device is jailbroken. Apple security system prevents the loading of any executable or dynamic library unless it is located in the $APPDIR directory *and* signed with the developer signature.

a-Shell works around this limitation by using WebAssembly executables. If you just run `clang main.c`, it will create a WebAssembly file `a.out`, which you can execute by just typing `a.out`.

If you really want to create an Arm64 executable (for example because you have a jailbroken device, or for any reasons), you will need: 
- to copy the iOS SDK to your local directory, 
- to unset the options that tell clang to create WebAssembly: `unsetenv CCC_OVERRIDE_OPTIONS` and `unsetenv SYSROOT`.
- after that, it should work. The errors you copy come from the link (`ld`) step, which is strange. It would be interesting to know what are the options that were passed to it.

**Comment by NeHyci** [comment]
Looks like the ld in app doesn't support building macho files, when I run ```ld --help```, it displays this:
```
ld: supported targets: elf
```
Is there are any way to make it support macho?

**Comment by NeHyci** [comment]
> - after that, it should work. The errors you copy come from the link (`ld`) step, which is strange. It would be interesting to know what are the options that were passed to it.

options:
```
[~/Documents]$ clang -target arm64-apple-darwin19.6.0 -isysroot iPhoneOS14.4.sdk main.o -v
clang version 14.0.0 (git@github.com:holzschu/llvm-project.git 06977076680100cc2b29ffd7f453026db9ac3f93)
Target: arm64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /private/var/mobile/Containers/Data/Application/42A6D41D-2D9B-4A42-B640-6A0D44CB4C1F/Documents
 "ld" -dynamic -arch arm64 -iphoneos_version_min 14.4.0 -syslibroot /var/mobile/Containers/Data/Application/42A6D41D-2D9B-4A42-B640-6A0D44C
B4C1F/Library/usr -o a.out main.o -lSystem
ld: error: unknown argument '-dynamic', did you mean '-Bdynamic'
ld: error: unknown argument '-arch'
ld: error: unknown argument '-iphoneos_version_min'
ld: error: unknown argument '-syslibroot'
ld: error: cannot open arm64: No such file or directory
ld: error: cannot open 14.4.0: No such file or directory
ld: error: cannot open /var/mobile/Containers/Data/Application/42A6D41D-2D9B-4A42-B640-6A0D44CB4C1F/Library/usr: Is a directory
ld: error: main.o: unknown file type
ld: error: unable to find library -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by NeHyci** [comment]
> Looks like the ld in app doesn't support building macho files, when I run ```ld --help```, it displays this:
> ```
> ld: supported targets: elf
> ```
> Is there are any way to make it support macho?

I found it. After clang builds the Object File, getting the lld to build the macho file requires some special options:
```
ld -flavor ld64.lld -arch arm64 -execute -platform_version ios 14 0 -adhoc_codesign main.o -o a.out /var/mobile/Containers/D
ata/Application/42A6D41D-2D9B-4A42-B640-6A0D44CB4C1F/Documents/iPhoneOS14.4.sdk/usr/lib/libSystem.tbd
```
