### ISSUE TITLE
Is it possible to customize a-shell’s prompt with .bashrc?

### ISSUE THREAD

**Issue by CarlyRaeJepsenStan** [holzschu/a-shell#568]
Hello friends, I would like to customize my a-shell prompt using a .bashrc or .bash_profile file.  While I’ve created and written to a .bashrc file in ~/Documents, there are no apparent changes to the appearance of my terminal.  This appears in contrast to my .vimrc file, which lives in ~/Documents and affects the appearance and action of my vim.  Is customization via bashrc possible and I’m just doing it wrong, or is it impossible due to permissions restrictions?

**Comment by holzschu** [comment]
Hi, 
the .bashrc file is actually read by a-Shell at the start of each new window, after with the .profile file.

However, a-Shell is only executing it lines by lines, not running the full bash shell on it (because, well, we don't have the full bash shell). So it's likely that there was a line before the prompt customization that caused the execution of the .bashrc to fail.

It would be easier to help you with the actual .bashrc and what you are trying to do.

**Comment by CarlyRaeJepsenStan** [comment]
Thanks for the quick response and sorry for the bother - the culprit was in fact simply deleting an errant space, then launching a new window.  I'm glad to know that .bashrc customization is possible!
