### ISSUE TITLE
How to run nmap?

### ISSUE THREAD

**Issue by naryfa** [holzschu/a-shell#579]
Hello,

Is it possible to run a pre-compiled nmap, traceroute, netstat or any other networking tools? 

I downloaded and tried using these, but they seem to just hang:

https://github.com/ernw/static-toolbox/releases/tag/nmap-v7.91SVN

**Comment by holzschu** [comment]
Any tool that has the same functionality as traceroute requires being run with root privilege, like traceroute. Since a-Shell cannot provide root privilege, it's impossible to have that kind of tools.

There is a pretty good explanation here by Roger Wolff (the maintainer of mtr): https://github.com/traviscross/mtr/issues/204#issuecomment-723961118 

nmap can run without root privilege, but it's very limited (just a scan of TCP ports).

**Comment by naryfa** [comment]
I see. Thank you for the explanation.
