### ISSUE TITLE
Only dash?

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#593]
It seems it is using `dash` instead of `bash` or `zsh` or something else. `dash` is simple and fast enough to run shell scripts, which also means I can't write a `.*shrc` pre-load script, beauty the prompt or set alias conveniently. I hope alternatives can be provided.

What's more, as many scripts are using `bash` grammars, many scripts have to be revised to suit a-shell.

**Comment by holzschu** [comment]
There are actually two shells :
- the default shell is a-Shell's own shell. It has its own command parser and prompt parser. At each new window, it opens `.profile` and `.bashrc` and executes each line in sequence. That is enough to beauty the prompt and set alias.
- `dash` is also available. You can start it with `sh` or `dash`. Before running, it loads `.profile` and executes it as a shell file. That is enough to beauty the prompt and set alias. 

`bash` is covered by the GPL, so it's part of those commands that I cannot port to iOS due to the FSF position.

**Comment by HeavySnowJakarta** [comment]
> There are actually two shells :
> 
> - the default shell is a-Shell's own shell. It has its own command parser and prompt parser. At each new window, it opens `.profile` and `.bashrc` and executes each line in sequence. That is enough to beauty the prompt and set alias.
> 
> - `dash` is also available. You can start it with `sh` or `dash`. Before running, it loads `.profile` and executes it as a shell file. That is enough to beauty the prompt and set alias. 
> 
> 
> 
> `bash` is covered by the GPL, so it's part of those commands that I cannot port to iOS due to the FSF position.

Thus, I hope there is a document to tell others so. I would have a research on how to configure it.
