### ISSUE TITLE
Anything should be noticed for jail broken devices?

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#609]
Inspired by #607, I'm concerned about what is special with jail broken devices, such as if `sudo` is available, what can be viewed (like `/etc/profile`), and if outside native binary files can be executed.

**Comment by holzschu** [comment]
I'm not 100 % certain, since I cannot test it myself, but I don't think outside native binary files can be executed, because `ios_system` only starts commands that have been defined in `commandDictionary.plist` or are WebAssembly files. For the same reason, `sudo` won't be available. However, a whole lot of files and directories will become readable (including `/etc/profile`). I've tried to keep changes to the source code of commands to a minimum, based on the assumption that these files would not be readable, and so they would not change anything. I'll fix the issue with `/etc/profile` and `dash` in the next release, but there may be other similar issues lurking.

**Comment by HeavySnowJakarta** [comment]
> I'm not 100 % certain, since I cannot test it myself, but I don't think outside native binary files can be executed, because `ios_system` only starts commands that have been defined in `commandDictionary.plist` or are WebAssembly files. For the same reason, `sudo` won't be available. However, a whole lot of files and directories will become readable (including `/etc/profile`). I've tried to keep changes to the source code of commands to a minimum, based on the assumption that these files would not be readable, and so they would not change anything. I'll fix the issue with `/etc/profile` and `dash` in the next release, but there may be other similar issues lurking.

You may want to provide a version just strengthened for jail broken devices by releasing ipa files, which is designed for reading more files and functions like sudo is available.

**Comment by holzschu** [comment]
I'll think about it, but it's not easy: for one, I have no way to test, and very little way to anticipate where the problems are coming from. Also, I can probably make it work for launching commands available in jailbroken devices, but it's unpredictable what happens when these commands start commands on their own (like sudo) : where is the output of the command?

**Comment by HeavySnowJakarta** [comment]
> I'll think about it, but it's not easy: for one, I have no way to test, and very little way to anticipate where the problems are coming from. Also, I can probably make it work for launching commands available in jailbroken devices, but it's unpredictable what happens when these commands start commands on their own (like sudo) : where is the output of the command? 

That's easy to understand, but after all, it's completely possible.
