### ISSUE TITLE
Clang -framework

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#622]
When building cmake on a-Shell for iOS with `bootstrap.sh` it occurs:

```
wasm-ld: error: unknown argument: -framework
wasm-ld: error: cannot open CoreFoundation: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation
)
Test failed to compile
Try: clang
Line: clang   -framework CoreFoundation   cmake_bootstrap_45982_test.c -o cmak
e_bootstrap_45982_test
```
I wonder what `-framework CoreFoundation` means. This issue is also available at https://gitlab.kitware.com/cmake/cmake/-/issues/24820.

**Comment by holzschu** [comment]
frameworks are the way Apple stores system libraries. This means the building script thinks it's building cmake on a Mac device, with the system libraries available. 

Instead, it should be building for WebAssembly. I don't think cmake has an option for WebAssembly, both for building and for using. In other words: even if you manage to compile cmake, it's very likely to be useless because it does not know the options for compiling with WebAssembly.
