### ISSUE TITLE
Sys/statvfs not found

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#627]
When compiling `unrar`:
```
clang++  -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DRAR_SMP -DUNRAR -c r
ar.cpp
In file included from rar.cpp:1:
In file included from ./rar.hpp:6:
./os.hpp:156:14: fatal error: 'sys/statvfs.h' file not
      found
    #include <sys/statvfs.h>
             ^~~~~~~~~~~~~~~
1 error generated.
*** Error code 1
```

**Comment by holzschu** [comment]
Usually, when a header file is not included, it is because the functions it defines are not included. That is the case here: WASI does not define statvfs(), probably because WASI does not expect having limitations related to the file system.

statvfs is probably being used to get the maximum path length. On iOS, that is MAXPATHLEN, defined as 1024.

**Comment by HeavySnowJakarta** [comment]
> Usually, when a header file is not included, it is because the functions it defines are not included. That is the case here: WASI does not define statvfs(), probably because WASI does not expect having limitations related to the file system.
> 
> 
> 
> statvfs is probably being used to get the maximum path length. On iOS, that is MAXPATHLEN, defined as 1024. 

Thus I have to revise the entire project. What a painful thing.
