### ISSUE TITLE
Files downloaded using yt-dlp nowhere to be found after messing a-Shell up by using it via Shortcuts

### ISSUE THREAD

**Issue by YX42** [holzschu/a-shell#701]
Usually my downloaded files appeared in the a-Shell folder on my iPad. Now they are nowhere to be found. I checked the Shortcuts folder and they are not in there. Also instead of [~documents]$ it says [~group]$ now. Sorry, I'm an absolute laymen

**Comment by holzschu** [comment]
The Shortcuts are executed in a separate directory, `~shortcuts`, `~group` or `$SHORTCUTS` (all three names are valid, and point to the same directory). This directory is not visible from the Files app.

Also, a-Shell tries to open the app in the last folder that was used the last time it was opened. Since it says `~group`, it is in the shortcuts folder. Try `ls` to see if your downloaded files are there. To see them in the Files app, I would use `mv fileName ~/Documents/`, to move them into the `~/Documents` folder, which is the one that is visible in the Files app.

Let me know if this doesn't answer your questions.

**Comment by YX42** [comment]
Thanks for the quick reply. I love your app!
This is what I get after using your command line:
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory

How do I get back to the ~documents directory? I'm still in ~group

**Comment by holzschu** [comment]
You need to replace `fileName` in the command with the name of the file you want to move (if there is one, check all files present in the directory with `ls`).

You can always get back to the `~/Documents` directory with `cd`, or `cd ~/Documents`.

**Comment by YX42** [comment]
Thank you!
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
actually only appears, when I enter a valid file name. I don't know how to proceed

**Comment by holzschu** [comment]
There must be something specific that escapes me. I'm going to need a screenshot in order to understand what is happening (with `ls`, the result of `ls`, the `mv` command and the result of the `mv` command).

**Comment by holzschu** [comment]
Thank you!
Now I get it: there are spaces in the file name, and it confuses `mv`. The best solution is to enclose the file name between quotes, to tell the system that the spaces are part of the file name:
```sh
mv "playlist [playlist].mp4" ~/Documents
```
That should work.

**Comment by YX42** [comment]
Thank you, it works now!

**Comment by YX42** [comment]
.
