### ISSUE TITLE
ffmpeg HEVC "Save Video" option missing

### ISSUE THREAD

**Issue by quinnaissance** [holzschu/a-shell#709]
I'm not sure if this is necessarily an a-Shell issue but I'm curious if anyone has any input. I noticed that if I use `yt-dlp` to download a (x264 mp4) video, and then run this:
```
ffmpeg -i in.mp4 -c:v hevc out.mp4
```
It converts fine, but if I then run `open` on the output file, the `Save Video` option to save it to one's Photos is not there, whereas it is on the input file.

It doesn't seem to be an issue with the conversion itself because the output video plays fine when run inside a player like VLC. Perhaps iOS is looking for some missing metadata?

**Comment by holzschu** [comment]
That's interesting. Is the output video playable by iOS own video player (what happens if you run `play out.mp4`?)
My intuition is that the `Save Video` option is only available for video files that iOS recognizes as video files (video files that are playable by iOS, as opposed to video files playable by VLC, which plays practically everything).

**Comment by quinnaissance** [comment]
Sorry this took a while to get back to, but I believe you were correct. Using `play` on the video gave me only audio, showing the QuickTime logo instead of the actual video. There may be some special ffmpeg settings required to produce iOS-friendly HEVC video. I have not yet figured that out.
