### ISSUE TITLE
lg2: Error pushing [-1] - Failed to authenticate SSH session: Unable to open public key file

### ISSUE THREAD

**Issue by damiencourousse** [holzschu/a-shell#712]
Since update to v1.12.2, lg2 reports an error on `push` to remotes:

```
Error pushing [-1] - Failed to authenticate SSH session: Unable to open public key file
```

My (working) setup has not changed since #696, so I don't see any culprit other than the recent upgrade.

**Comment by holzschu** [comment]
I'm going to have a look. I assume the other lg2 commands are working normally?

**Comment by holzschu** [comment]
I've tried pushing on my machines, and it works. I think the main clue is "Unable to open public key file": the issue is not during the connection, but in the location of the public key file. How did you specify it? It's in the `.gitconfig` file, I think.

(Each update changes the location of the main directory. If you specify file locations using `~`, that remains valid across updates. If you used the explicit file path, `/private/var/mobile/Containers/Data/Application/<UUID>/`, it does not).

**Comment by damiencourousse** [comment]
You were right, I used an absolute path to specify the location of the private key file, and the home dir was set to a new location after an update.  Using tilde expansion works fine, it avoids this issue.

Thanks for the quick feedback, and my apologies for not replying sooner.
