### ISSUE TITLE
caps-lock key ≠ escape anymore

### ISSUE THREAD

**Issue by r32gtr** [holzschu/a-shell#730]
im a total newbie and use a-shell primarily so that i can use vim to code on my ipad at uni instead of a big laptop. problem im facing is that caps lock no longer functions as an escape key and im forced to switch windows so i can leave insert mode.

a-shell settings has the setting turned on as well. love the app though! worth every penny

**Comment by holzschu** [comment]
Hi, I tried on my end, and both methods to redefine caps-lock as escape are working on my iPad. I assume you mean with an external keyboard (because otherwise you'd be using the escape key on the toolbar).

Just checking: in the Settings app, go to General, then Keyboard, then Hardware Keyboard, then Modifier Keys, and you can change "Caps Lock" to "Escape" here. There is also a modifier to "Enable Caps Lock" (in Settings->General->Keyboard). That one should work, even if the a-Shell settings doesn't.

**Comment by r32gtr** [comment]
appreciate you! that worked very well
