### ISSUE TITLE
Feature Suggestion: “Find within a page” and “Back” button in the Internal Browser?

### ISSUE THREAD

**Issue by jiang-qian** [holzschu/a-shell#737]
The internalbrowser you just implemented is an absolute lifesaver for the server based applications (for example the SilverDict dictionaries and the Diogenes text reading system for Greek and Latin authors) and it is invaluable even for more ordinary use scenarios like browsing local version of a website (since safari does not have access to local files!).  So some improvements of this critical new function would make it even more useful.

One is finding within a page. It is just a button (or keyboard shortcut though given iOS is mostly touch based this would be less useful)  that when pressed give a dialog so that once you put in the search term the internalbrowser will search for items within the webpage being displayed. This will be extremely useful when the page being displayed (like a dictionary entries or a long text of an ancient author) is very long and one need to quickly find a specific passage within it.

Another would be a back button or keyboard shortcut. This just go back to the previous page. Sometimes the page being displayed has link that when clicked will open. Being able to go back would be super nice.

Finally, if the internal browser can allow open a new page in a tabbed system that would be super useful. However I assume that would be much harder to implement.

Again, with internalbrowser a-shell ha become an astonishingly useful piece of software and has opened up the previously closed iOS/iPadOS system to immensely broader range of applications! Thank you again for developing a-Shell and continually improving it!

**Comment by holzschu** [comment]
Hi, 
the internalbrowser is minimalist by design: it will display what you send it, with minimum interference. This gives users maximal control, but it also means that some actions will not be implemented in the browser. But they can be implemented in the page being displayed, using JavaScript. If you do not want to write JavaScript code (which I understand), there are still options available:
- if you have an external keyboard connected, command-F will open the "Find" dialog. Without an external keyboard, long-click on a word (any word). A pop-up dialogue appears, click on "Find Selection". Then you cand edit the text being searched and search on the page.
- left-edge-swipe will move back one page, right-edge-swipe will move forward one page.
- as you said, a tabbed system is too difficult to implement. The available options are to use the multi-window system, with `newWindow`, and an internalbrowser running in each window, or find JavaScript code that does it.

**Comment by jiang-qian** [comment]
Being novice to iOS I wasn’t aware of these options! Yes they work very well for my purpose and there is no need for doing anything more with the internalbrowser 

Again thank you for making such a useful piece of software!
