### ISSUE TITLE
ReferenceError: WebAssembly Packages have Stopped Functioning

### ISSUE THREAD

**Issue by xloem** [holzschu/a-shell#805]
It’s been a while since I’ve used a-Shell and it doesn’t seem to work anymore now when I try. The App Store says I am up to date.

```

[~/Documents]$ pkg install xz
Downloading xz
Downloading xz + xzdec
Downloading man pages
Done
[~/Documents]$ xz -d file.cpp.xz
wasm: ReferenceError: Can't find variable: WebAssembly
```
```
[~/Documents]$ pkg install base64
Downloading base64
Done
[~/Documents]$ base64 file.cpp.xz
wasm: ReferenceError: Can't find variable: WebAssembly
```

**Comment by holzschu** [comment]
I'm unable to reproduce this issue. I'm also confident that "xz" is part of the packages that are installed by default (on a-Shell, but not on a-Shell mini).

All downloadable commands are compiled to WebAssembly, and a-Shell uses Apple's own webAssembly engine (because it's there), so the error message you get is straight from the system. My guess is that something disabled the WebAssembly engine on your iPad. The "Lockdown mode" on iOS can have this effect.

**Comment by xloem** [comment]
That’ it! I have lockdown mode enabled! Thanks a bunch.

It looks like apps can detect this, safari displays a banner about it.

**Comment by holzschu** [comment]
I'm working on getting rid of Apple's WebAssembly interpreter; that will fix this issue as well.
