### ISSUE TITLE
.ssh dir not in $HOME

### ISSUE THREAD

**Issue by jgte** [holzschu/a-shell#875]
First of all, thank you very much for this extremely nice terminal app.

I share my .ssh dir with OSX and Ubuntu machines. As is the case in normal distros, the .ssh/config file references the ssh keys of every connection relative to to the ~/.ssh dir, e.g. `Identityfile ~/.ssh/id_rsa.something`, since the .ssh dir is located in ~ (i.e., $HOME).

I’ve run into the issue that in a-shell, the .ssh dir is in ~/Documents/.ssh and this prevents the ssh command from finding the ~/.ssh/<key files>. I get `no such identity: /private/var/mobile/Containers/Data/Application/…/.ssh/id_rsa.something: No such file or directory`

I’ve tried soft-linking ~/Documents/.ssh to ~ /.ssh but i get `ln: ./.ssh: Operation not permitted`.

Other than editing the entries to `Identityfile` my .ssh/config, which is not a big deal with awk, is there any advisable approach to overcome a-shell’s inconsistency location of the .ssh dir and $HOME?

**Comment by holzschu** [comment]
You have a very good understanding of the issue. The problem is that for iOS, $HOME is not accessible for writing by the user, only ~/Documents, ~/Library and ~/tmp are.  Hence all configuration files are in ~/Documents. 

I had not anticipated a .ssh directory being shared with other machines. That obviously results in the issue you encounter. I see multiple fixes:
- the easiest is probably changing the file with awk, as you said
- according to “man ssh_config”, you can use environment variables in the config file, using ${} syntax; something like ${SSH_HOME} would refer to $HOME/Documents on iOS and to $HOME on other computers (I haven’t tested this)
- the last one depends on the other commands you use with a-Shell. You can always redefine $HOME to ~/Documents (more likely to $SSH_HOME to avoid issues with redefinitions) in your .profile, but some system calls also use this environment variable, so you would see some side effects. The most obvious is the apparition of ~/Documents/tmp, there might be others.

**Comment by jgte** [comment]
I tried implementing a [few scripts](https://github.com/jgte/ssh-config-a-shell) to handle concurrent `.ssh/config` and an a-Shell specific `.ssh/config.a-Shell` but I run into a number of issue that I have no time to figure out (see at the end of the [readme](https://github.com/jgte/ssh-config-a-shell/blob/main/README.md)).
