### ISSUE TITLE
Lack of ... 2>&1 | ... causes Vim's make command to act unexpectedly.

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#94]
`:make` acts unexpectedly in Vim! 

When I type `:make`, Vim reports that it ran something similar to `make  2>&1| tee /private/.../tmp/some/tempfile`. Make runs, as expected, but does not appear to send its output to Vim! Additionally, a new file, &1 is created in the current directory.

Thank you!

**Comment by personalizedrefrigerator** [comment]
https://github.com/holzschu/ios_system/issues/4 suggests that `ios_system` does have support for `2>&1` output redirection, however, when I run,
```sh
$ echo "Testing..." 2>&1 | cat
$ 
$ cat &1
Testing...
$ 
```

On my Ubuntu system, 
```bash
...:~$ sh
$ echo "Testing..." 2>&1 | cat
Testing ...
$ 
```

I hope this is helpful!

**Comment by holzschu** [comment]
Indeed, that should work (I wrote code for that) and yet it doesn’t. I’ll have a look into why the code is not triggered. 

I must warn you that `:make` still won’t work because the command does not exist (yet), but that’s another story. Both issues are on the todo list, `2>&1` with a high priority.

**Comment by personalizedrefrigerator** [comment]
Thank you! 
However, as I'm using a very limited [python implementation of make](https://github.com/personalizedrefrigerator/AlmostMake), `2>&1` should fix it!

**Comment by holzschu** [comment]
Hi, 
the issue should be fixed with build 110, currently in TestFlight (https://testflight.apple.com/join/WUdKe3f4) 
If you confirm that the fix works, I'll move it to the AppStore version. 

Would you be interested in adding your python implementation of make to the AppStore version too? (with proper credits, of course). I'm working on a full port of make, but it will be months before I can make it work (with all the other things on the list).

**Comment by personalizedrefrigerator** [comment]
It seems to work! 
Additionally, I would be happy to have AlmostMake added to a-Shell! Note, however, that the tests won't run because a-Shell doesn't support ';' command separators. E.g. `cd directory; echo 2` tries to `cd` to `directory;` instead of `directory`.
Thank you!

**Comment by personalizedrefrigerator** [comment]
**Update** AlmostMake [is now available on PyPI!](https://pypi.org/project/almost-make-personalizedrefrigerator/)

**Comment by personalizedrefrigerator** [comment]
Additional note: Mozilla's [Pymake](http://benjamin.smedbergs.us/pymake/) is MIT-licensed.
